// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Club struct {
	ID   uuid.UUID
	Name string
}

type User struct {
	ID        uuid.UUID
	Nickname  string
	Img       sql.NullString
	Country   sql.NullString
	City      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Deleted   sql.NullBool
}

type UserClub struct {
	UserID uuid.UUID
	ClubID uuid.UUID
}
